wiki/wiki/encyclopedia/urls.py
from django.urls import path

from . import views
app_name='encyclopedia'
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>/",views.displayer, name="displayer"),
    path("search/", views.search,name="search"),
    path("create/", views.create, name = "create"),
    path("edit/",views.edit, name="edit"),
    path("save_edit/",views.save_edit,name="save_edit"),
    path("random/",views.random_page,name="random_page")
]

wiki/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path
from encyclopedia import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
   
    #path('wiki/',include("encyclopedia.urls"))
]

wiki/wiki/encyclopedia/models.py
from django.db import models
from . import util  
# Create your models here.

wiki/wiki/encyclopedia/views.py
import random
from django.shortcuts import render
from markdown2 import Markdown
from django import forms
from . import util

def index(request):
    return render(request,"encyclopedia/index.html", {
        "entries": util.list_entries(),
        "page": "All Pages"
    }) 

def displayer(request,title):  
    markdowner=Markdown()
    if util.get_entry(title) is None:
        return render(request,"encyclopedia/entry.html",{
            "content":f"error: requested \"{title}\"- page was not found"
        }) 
    return render(request,"encyclopedia/entry.html",{
        "title":title,
        "content":markdowner.convert(util.get_entry(title)),
    })
def search(request):
    if request.method == "POST":
        entry_search = request.POST['q']
        if util.get_entry(entry_search) is None:
            content=None
        else:
            content = Markdown().convert(util.get_entry(entry_search))
        if content is not None:
            return render(request,"encyclopedia/entry.html",{
                "title":entry_search,
                "content":content
            })
        else:
            all_entries=util.list_entries()
            results = []
            for entry in all_entries:
                if entry_search.lower() in entry.lower():
                    results.append(entry)
            return render(request,"encyclopedia/search.html",{
                "results":results
            })

def create(request):
    if request.method == "GET":
        return render(request, "encyclopedia/create.html")
    else:
        title = request.POST['title']
        content = request.POST['content']
        is_title_exist = util.get_entry(title)
        if is_title_exist is not None:
            return render(request,"encyclopedia/entry.html",{
                "content":f"error: Entry already exists"
            })
        else:
            util.save_entry(title,content)
            converted_html = Markdown().convert(util.get_entry(title))
            return render(request,"encyclopedia/entry.html",{
                "title":title,
                "content":converted_html
            })

def edit(request):
    if request.method == "POST":
        title = request.POST['entry_title']
        content = util.get_entry(title)
        return render(request, "encyclopedia/edit.html",{
            "title":title,
            "content":content 
        })

def save_edit(request):
    if request.method == "POST":
        title = request.POST['title']
        content = request.POST['content'] #bu content markdown content, renderdaki contente atamadan once bunu html'e cevirmek lazim
        util.save_entry(title,content)
        converted_html = Markdown().convert(util.get_entry(title))
        return render(request, "encyclopedia/entry.html", {
            "title":title,
            "content":converted_html
        })
def random_page(request):
    all_entries=util.list_entries()
    title_of_random=random.choice(all_entries)
    converted_html=Markdown().convert(util.get_entry(title_of_random))
    return render(request,"encyclopedia/entry.html",{
        "title":title_of_random,
        "content":converted_html
    })

wiki/wiki/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
   {{title}}
{% endblock %}

{% block body%}
    <h1>New Page</h1>
    <form action="{% url 'encyclopedia:create' %}" method="POST">
        {% csrf_token%}
        <label for="title">Title</label>
        <input type="text" name="title" id="title" placeholder="Enter a title">
        <br/>
        <label for="content">Content</label>
        <br/>
        <textarea name="content" placeholder="Enter content here"></textarea>
        <input type="submit" value="save" class="btn btn-primary">
    </form>
{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
   {{title}}
{% endblock %}

{% block body%}
    <h1>Edit {{ title }}</h1>
    <form action="{% url 'encyclopedia:save_edit' %}" method="POST">
        {% csrf_token%}
        <label>Title</label>
        <input type="text" name="title" value="{{ title }}">
        <br/>
        <label>Content</label>
        <br/>
        <textarea name="content">{{ content }}</textarea>
        </br>
        <input type="submit" value="Edit" class="btn btn-primary">
    </form>
{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
   {{title}}
{% endblock %}

{% block body%}
    {{content|safe}}
    <form action="{% url 'encyclopedia:edit' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="entry_title" value="{{ title }}">
        <input type="submit" value="Edit" class="btn btn-secondary">
    </form>
{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body%}
    <h1>{{page|safe|escape}}</h1>
    <ul>
        {% for entry in entries %}
        <li><a href="{% url 'encyclopedia:displayer' title=entry %}" >{{ entry }}</a></li>
        {% endfor %}
    </ul>
 

{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="POST" >
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_page'%}"> Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body%}
    <h1>Search results</h1>
    <ul>
        {% for entry in results %}
        <li><a href="{% url 'encyclopedia:displayer' title=entry %}" >{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}